<div id="caixa_login" class="col-lg-12">
    <div class="title">
        <h2>Criar um modulo</h2>
    </div>
    <div class="form col-lg-6">
        <form action="" method="post">
        	<b><?php echo $this->mensagemForm ?></b>
            <div class="">
                <label>Nome do modulo</label>
                <input type='text' class="form-control" name='nomeModulo' id='nomeModulo' />
            </div>
            <div>
                <button id="" >Gerar</button>
            </div>
        </form>
    </div>
</div>