<?php echo $this->partial("layout/head.phtml") ?>
<?php echo $this->partial("layout/top.phtml") ?>
<div class="container-fluid">
    <div class="row">
        <?php echo $this->partial("layout/menu.phtml") ?>
        <div ng-app="app" class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
			<?php echo $this->content; ?>
		</div>
    </div>
</div>
<script type="text/javascript" src="/js/angular/app.js"></script>
<script type="text/javascript" src="/js/angular/service.js"></script>
<script type="text/javascript" src="/js/angular/usuario/controller.js"></script>
<?php echo $this->partial("layout/foot.phtml") ?>