<div id="caixa_login" class="col-lg-12">
    <div class="title">
        <h2>Área restrita</h2>
    </div>
    <div class="form col-lg-6">
        <form action="" method="post">
            <div class="">
                <label>Usuário</label>
                <input type='text' class="form-control" name='' id='' />
            </div>
            <div class="">
                <label>Senha</label>
                <input type='text' class="form-control" name='' id='' />
            </div>
            <div>
                <button id="" >Entrar</button>
            </div>
        </form>
    </div>
</div>